import {
    Type,
    Color
} from '../constants'
export const getBoard = ()=>{
    return [{
        rank:"1",
        file:"a",
        color:Color.WHITE,
        type:Type.ROOK
    },{
        rank:"1",
        file:"b",
        color:Color.WHITE,
        type:Type.KNIGHT
    },{
        rank:"1",
        file:"c",
        color:Color.WHITE,
        type:Type.BISHOP
    },{
        rank:"1",
        file:"d",
        color:Color.WHITE,
        type:Type.QUEEN
    },{
        rank:"1",
        file:"e",
        color:Color.WHITE,
        type:Type.KING
    },{
        rank:"1",
        file:"f",
        color:Color.WHITE,
        type:Type.BISHOP
    },{
        rank:"1",
        file:"g",
        color:Color.WHITE,
        type:Type.KNIGHT
    },{
        rank:"1",
        file:"h",
        color:Color.WHITE,
        type:Type.ROOK
    },
    {
        rank:"2",
        file:"a",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"b",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"c",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"d",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"e",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"f",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"g",
        color:Color.WHITE,
        type:Type.PAWN
    },{
        rank:"2",
        file:"h",
        color:Color.WHITE,
        type:Type.PAWN
    },
    {
        rank:"8",
        file:"a",
        color:Color.BLACK,
        type:Type.ROOK
    },{
        rank:"8",
        file:"b",
        color:Color.BLACK,
        type:Type.KNIGHT
    },{
        rank:"8",
        file:"c",
        color:Color.BLACK,
        type:Type.BISHOP
    },{
        rank:"8",
        file:"d",
        color:Color.BLACK,
        type:Type.QUEEN
    },{
        rank:"8",
        file:"e",
        color:Color.BLACK,
        type:Type.KING
    },{
        rank:"8",
        file:"f",
        color:Color.BLACK,
        type:Type.BISHOP
    },{
        rank:"8",
        file:"g",
        color:Color.BLACK,
        type:Type.KNIGHT
    },{
        rank:"8",
        file:"h",
        color:Color.BLACK,
        type:Type.ROOK
    },
    {
        rank:"7",
        file:"a",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"b",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"c",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"d",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"e",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"f",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"g",
        color:Color.BLACK,
        type:Type.PAWN
    },{
        rank:"7",
        file:"h",
        color:Color.BLACK,
        type:Type.PAWN
    }
    ];
}